### ISSUE TITLE
Hedge mage set invisible bug

### ISSUE THREAD

**Issue by Ashensakar** [ForgottenGlory/Living-Skyrim-3#6]
**LS Version**
2.3.2

**Describe the bug**
gear that you have when you first created (the hedge mage set) has no look, your body is invincible 

**To Reproduce**
wear hedge set

**Expected behavior**
to have textures.

**Screenshots**
![Screenshot 2021-02-01 133302](https://user-images.githubusercontent.com/68168803/106465554-0792dc00-6492-11eb-818c-fc71803ccf13.png)

**Additional context**

**Comment by TwistedModding** [comment]
This mod fixes it: https://www.nexusmods.com/skyrimspecialedition/mods/40967

Should be fine for female characters at the moment

**Comment by ForgottenGlory** [comment]
Will fix Beta 2, probably just going to remove Hedge Mage armor from the inventory at character creation since it's craftable as well

**Comment by daffodilian** [comment]
No male model for the armor by default, there's a mod to allow it for males, we'll look into adding that

**Comment by ForgottenGlory** [comment]
Fixed Beta 2

**Comment by celadoneiron** [comment]
The file structure for the "Hedge Mage Armor - Male Version" mod is incorrect, so the set still doesn't appear on male characters in game. The "meshes" folder and its contents need to be moved outside the included "data" folder, after which the data folder can be deleted.

Before:
![Screen Shot 02-27-21 at 10 28 AM](https://user-images.githubusercontent.com/73095714/109369411-f9e14280-78e7-11eb-9329-3fc953b8c7c1.PNG)

After:
![Screen Shot 02-27-21 at 10 29 AM](https://user-images.githubusercontent.com/73095714/109369418-01085080-78e8-11eb-868e-d3e6f6bd5645.PNG)

Thanks to Lucifer MorningSloth in the Discord for bringing this to my attention.

**Comment by ForgottenGlory** [comment]
Fixed for full release
